---
apiVersion: v1
kind: Namespace
metadata:
  name: floating-ip
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: floating-ip
  namespace: floating-ip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floating-ip
  namespace: floating-ip
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - replicasets
    - endpoints
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - list
    - patch
    - get
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: floating-ip
subjects:
- kind: ServiceAccount
  name: floating-ip
  namespace: floating-ip
roleRef:
  kind: ClusterRole
  name: floating-ip
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: floating-ip
  namespace: floating-ip
type: Opaque
stringData:
  PROVIDER_AUTH: ${provider_auth}
  PROVIDER: ${provider}
  FLOATING_IP: ${floating_ip}
  ZONE: ${zone}