---
apiVersion: v1
kind: Namespace
metadata:
  name: hcloud-ip-floater
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hcloud-ip-floater
  name: hcloud-ip-floater
  namespace: hcloud-ip-floater
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hcloud-ip-floater
  name: hcloud-ip-floater
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hcloud-ip-floater
  name: hcloud-ip-floater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hcloud-ip-floater
subjects:
- kind: ServiceAccount
  name: hcloud-ip-floater
  namespace: hcloud-ip-floater
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hcloud-ip-floater
  name: hcloud-ip-floater
  namespace: hcloud-ip-floater
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hcloud-ip-floater
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hcloud-ip-floater
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: hcloud-ip-floater-secret-env
        - configMapRef:
            name: hcloud-ip-floater-config-env
            optional: true
        image: costela/hcloud-ip-floater:v0.1.4
        name: hcloud-ip-floater
      serviceAccountName: hcloud-ip-floater
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-ip-floater-secret-env
  namespace: hcloud-ip-floater
stringData:
  HCLOUD_IP_FLOATER_HCLOUD_TOKEN: ${hcloud_token}
  HCLOUD_IP_FLOATER_LOG_LEVEL: info