clusters:
- cluster:
    server: https://k8s-api.${domain}
  name: ${domain}
contexts:
- context:
    cluster: ${domain}
    user: ${domain}
  name: ${domain}
current-context: ${domain}
users:
- name: ${domain}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - k8s
        - exec-credential
        - https://k8s-api.${domain}
      command: pomerium-cli
      env: null
      installHint: |
        pomerium-exec-plugin is required to authenticate
        to the current cluster.  It can be installed via go-get:

        On macOS: brew tap pomerium/tap && brew install pomerium-cli
        On Ubuntu: curl -L https://github.com/pomerium/pomerium/releases/download/v0.14.4/pomerium-cli-linux-amd64.tar.gz | tar -z -x
        On Windows: curl -L https://github.com/pomerium/pomerium/releases/download/v0.14.4/pomerium-cli-windows-amd64.zip | tar -z -x
        To set the context, run: KUBECONFIG=~/.kube/config:$PWD/${domain}-exec.yaml kubectl config view --flatten > ~/.kube/config.tmp && \
        mv ~/.kube/config.tmp ~/.kube/config