apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: self-signed-cert
  namespace: default
spec:
  commonName: ${domain}
  secretName: self-signed-cert
  dnsNames:
    - ${domain}
    - "*.${domain}"
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: self-signed-cert
  namespace: kube-system
spec:
  commonName: ${domain}
  secretName: self-signed-cert
  dnsNames:
    - ${domain}
    - "*.${domain}"
  issuerRef:
    name: self-signed
    kind: ClusterIssuer