apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  # affinity:
    # nodeAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
        # nodeSelectorTerms:
        # - matchExpressions:
          # - key: node-role.kubernetes.io/master
            # operator: DoesNotExist
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.15.2
  containers:
  - name: prometheus-config-reloader
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
  - name: rules-configmap-reloader
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
  # nodeSelector:
    # kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 1
  resources:
    requests:
      memory: 350Mi
      cpu: 75m
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.15.2
