apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: akrobateo
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: akrobateo
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - replicasets
    - nodes
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - ""
    resources:
    - services/status
    verbs:
    - update
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: akrobateo
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: akrobateo
  subjects:
  - kind: ServiceAccount
    name: akrobateo
    namespace: kube-system
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: akrobateo
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: akrobateo
    template:
      metadata:
        labels:
          name: akrobateo
      spec:
        containers:
        - env:
          - name: WATCH_NAMESPACE
            value: ""
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: akrobateo
          - name: LB_IMAGE
            value: lukasauerbeck/akrobateo-lb-mirror
          image: lukasauerbeck/akrobateo-mirror:latest #registry.pharos.sh/kontenapharos/akrobateo:latest
          imagePullPolicy: Always
          name: akrobateo
          resources:
            limits:
              cpu: 100m
              memory: 40M
            requests:
              cpu: 50m
              memory: 20M
        serviceAccountName: akrobateo
kind: List
metadata: {}
