name: Generate terraform docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Render terraform docs in deploy subfolders and push changes back to branch
      uses: terraform-docs/gh-actions@v0.6.1
      with:
        find-dir: deploy/
        output-file: README.md
        output-method: print
        git-push: "false"